wemall:
  print:
    client_id: 1062187632
    client_secret: 3
    machine_code: 4004655528
  wx:
    app-id: #
    app-secret: #
    mch-id: 1581776861
    mch-key: s#
    notify-url: #
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: classpath:apiclient_key.pem
  #通知相关配置
  notify:

    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    # 阿里云短信
    aliyunsms:
      enable: true
      accessKeyId: #
      secret: #
      location: cn-hangzhou
      signName: 立刻U
      templateId: #
    wx:
      enable: true
      checkoutSuccess: #
      deliverySubscribeId: #
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: aliyun
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8080/wx/storage/fetch/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: #
      accessKeyId: #
      accessKeySecret: #
      bucketName: test-jungle
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: litemall
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: litemall